[build]
command = "hugo --cleanDestinationDir --gc --minify --environment production --printPathWarnings --printI18nWarnings --panicOnWarning"
publish = "public"

[build.environment]
GO_VERSION = "1.27.0"
HUGO_VERSION = "0.165.0"
HUGO_ENVIRONMENT = "production"

